openapi: 3.0.2
info:
  title: record store
  version: '1.0'
  description: Database related APIs
  contact:
    email: contact@hdwlab.co.jp
    name: Human Dataware Lab. Co. Ltd.
    url: 'http://www.hdwlab.co.jp/'
  license:
    name: Apache-2.0
servers:
  - url: 'http://localhost:8080'
paths:
  '/{database_id}/records/{record_id}':
    get:
      operationId: getRecord
      description: Return the detail of the record.
      parameters:
        - name: database_id
          in: path
          required: true
          description: ID of the target database
          schema:
            type: string
        - name: record_id
          in: path
          required: true
          description: record_id
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples: {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecordDetailModel'
              examples: {}
      summary: Get detail information of the record
      tags:
        - record
  '/{database_id}/records':
    get:
      operationId: listRecords
      description: Return the list of records.
      parameters:
        - name: database_id
          in: path
          required: true
          description: ID of the target database
          schema:
            type: string
        - name: per_page
          description: Number of items to return per page
          in: query
          schema:
            type: integer
        - name: page
          description: Page number
          in: query
          schema:
            type: integer
        - name: sort_key
          description: Key to sort
          in: query
          schema:
            type: string
        - name: search
          description: Search keyword for name of records
          in: query
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecordListModel'
              examples: {}
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples: {}
      summary: Get list of records
      tags:
        - record
    parameters: []
components:
  schemas:
    RecordModel:
      title: Record
      type: object
      properties:
        record_id:
          type: string
          minLength: 1
        start_timestamp:
          type: number
        end_timestamp:
          type: number
        tags:
          type: array
          items:
            type: string
        duration:
          type: number
      required:
        - record_id
        - start_timestamp
        - end_timestamp
    RecordListModel:
      title: RecordListModel
      type: object
      properties:
        database_id:
          type: string
          minLength: 1
        records:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            $ref: '#/components/schemas/RecordModel'
        number_of_pages:
          type: number
      required:
        - database_id
        - records
        - number_of_pages
      x-examples:
        example-1:
          database_id: default
          records:
            - record_id: '016_00000000030000000240'
              start_timestamp: 1489728491
              end_timestamp: 1489728570.957
              tags:
                - ''
                - timestamps
                - center
                - camera
                - front
              duration: 79.95700001716614
            - record_id: 20191001_094731_000_car3
              start_timestamp: 1569893086.44
              end_timestamp: 1569893087.39
              tags:
                - raw
                - can
                - vehicle
                - ''
              duration: 0.9500000476837158
            - record_id: B05_17000000010000000829
              start_timestamp: 1517463303
              end_timestamp: 1517463303.95
              tags:
                - ''
                - speed
                - turn
                - analog
                - brake
                - ',vehicle'
                - signal
                - pulse
                - vehicle
                - back
                - gnss
                - acceleration
              duration: 0.9500000476837158
            - record_id: sample
              start_timestamp: 1550125637.22
              end_timestamp: 1550125637.53
              tags:
                - ''
                - downsampled
                - lidar
              duration: 0.309999942779541
          number_of_pages: 1
    RecordDetailModel:
      title: RecordDetailModel
      type: object
      properties:
        database_id:
          type: string
          minLength: 1
        record_id:
          type: string
          minLength: 1
        record_info:
          type: object
          required:
            - record_id
            - start_timestamp
            - end_timestamp
            - tags
            - duration
          properties:
            record_id:
              type: string
              minLength: 1
            start_timestamp:
              type: number
            end_timestamp:
              type: number
            tags:
              type: array
              items:
                type: string
            duration:
              type: number
        contents:
          type: array
          items:
            type: string
        files:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              path:
                type: string
                minLength: 1
              record_id:
                type: string
                minLength: 1
              type:
                type: string
                minLength: 1
              content-type:
                type: string
                minLength: 1
              start_timestamp:
                type: number
              end_timestamp:
                type: number
            required:
              - path
              - record_id
              - type
              - content-type
              - start_timestamp
              - end_timestamp
      required:
        - database_id
        - record_id
        - record_info
        - contents
        - files
      x-examples:
        example-1:
          database_id: default
          record_id: '016_00000000030000000240'
          record_info:
            record_id: '016_00000000030000000240'
            start_timestamp: 1489728491
            end_timestamp: 1489728570.957
            tags:
              - timestamps
              - camera
              - center
              - front
            duration: 79.95700001716614
          contents:
            - camera/front-center
          files:
            - path: /records/016_00000000030000000240/data/camera_01_timestamps.csv
              record_id: '016_00000000030000000240'
              type: raw_data
              content-type: text/csv
              start_timestamp: 1489728491
              end_timestamp: 1489728570.957
tags:
  - name: record
