openapi: 3.0.2
info:
  title: schema
  version: '1.0'
  description: Database related APIs
  contact:
    email: contact@hdwlab.co.jp
    name: Human Dataware Lab. Co. Ltd.
    url: 'http://www.hdwlab.co.jp/'
  license:
    name: Apache-2.0
servers:
  - url: 'http://localhost:8080'
paths:
  '/databases/{database_id}':
    get:
      operationId: retrieveDatabase
      description: Return information of the database.
      parameters:
        - name: database_id
          in: path
          required: true
          description: ''
          schema:
            type: string
      summary: Get detail information of the database
      tags:
        - database
        - get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Database'
              examples: {}
  /databases:
    get:
      operationId: listDatabases
      description: Return the list of databases.
      parameters:
        - name: per_page
          description: Number of items to return per page
          in: query
          schema:
            type: integer
        - name: page
          description: Page number
          in: query
          schema:
            type: integer
        - name: sort_key
          description: Key to sort
          in: query
          schema:
            type: string
        - name: search
          description: Search keyword for name of databases
          in: query
          schema:
            type: string
      summary: Get list of database
      tags:
        - database
        - list
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatabaseList'
    parameters: []
components:
  schemas:
    DatabaseList:
      type: object
      title: DatabaseList
      properties:
        count:
          type: integer
        number_of_pages:
          type: integer
        databases:
          type: array
          items:
            $ref: '#/components/schemas/Database'
      x-examples:
        example-1:
          count: 1
          databases:
            - database_id: small_driving_behavior_database
              name: Small Driving Behavior Database
              description: ''
          number_of_pages: 1
    Database:
      title: Database
      type: object
      properties:
        database_id:
          type: string
        name:
          type: string
        description:
          type: string
      required:
        - database_id
      x-examples:
        example-1:
          database_id: small_driving_behavior_database
          name: Small Driving Behavior Database
          description: ''
        example-2:
          database_id: default
          name: default database
          description: default database located in "/share/small_DrivingBehaviorDatabase"
