openapi: 3.0.2
info:
  title: content store
  version: '1.0'
  description: Retrieve content of record
  contact:
    email: contact@hdwlab.co.jp
    name: Human Dataware Lab. Co. Ltd.
    url: 'http://www.hdwlab.co.jp/'
  license:
    name: Apache-2.0
servers:
  - url: 'http://localhost:8080'
paths:
  '/{database_id}/raw':
    parameters:
      - schema:
          type: string
        name: database_id
        in: path
        required: true
    get:
      summary: Get content
      tags:
        - content
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
        '400':
          description: Bad Request
        '404':
          description: Not Found
      operationId: getContent
      description: 'Return single content, even if multiple contents is found.'
      parameters:
        - schema:
            type: string
          in: query
          name: record_id
          description: Record ID
          required: true
        - schema:
            type: string
          in: query
          name: content
          description: Content name
          required: true
        - schema:
            type: number
          in: query
          name: start_timestamp
          description: Timestamp to extract content from
        - schema:
            type: number
          in: query
          name: end_timestamp
          description: Timestamp to extract content to
    post:
      summary: Create content
      operationId: createContent
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '409':
          description: Conflict
      description: 'Create content. If content already exists, this operation will fail.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                metadata:
                  type: object
                data:
                  type: object
              required:
                - metadata
                - data
    put:
      summary: Update content
      operationId: updateContent
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '409':
          description: Conflict
      description: 'Update content. Only when one record is found, this method succeed.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: object
                  required:
                    - record_id
                    - content
                  properties:
                    database_id:
                      type: string
                    record_id:
                      type: string
                    sub_record_id:
                      type: string
                    content:
                      type: string
                data:
                  type: object
              required:
                - query
                - data
        description: query is a part of record's identity.
components:
  schemas:
    Content:
      title: Contents
      type: object
      properties:
        metadata:
          type: object
        timestamps:
          type: array
          items: {}
        data:
          type: array
          items: {}
        columns:
          type: array
          items: {}
      required:
        - metadata
        - timestamps
        - data
        - columns
tags:
  - name: content
