version: '3'
services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '30071:80'
    depends_on:
      - prism_1
      - prism_2
      - prism_3
  prism_1:
    image: stoplight/prism:3
    volumes:
      - ../:/ref:ro
    command: >
      mock -p 4010 --host 0.0.0.0 /ref/api.v1.databases.yaml
  prism_2:
    image: stoplight/prism:3
    volumes:
      - ../:/ref:ro
    command: >
      mock -p 4010 --host 0.0.0.0 /ref/api.v1.databases.records.yaml
  prism_3:
    image: stoplight/prism:3
    volumes:
      - ../:/ref:ro
    command: >
      mock -p 4010 --host 0.0.0.0 /ref/api.v1.databases.jobs.yaml
