openapi: 3.0.2
info:
  title: permission store
  version: '1.0'
  description: Permision manage APIs
  contact:
    email: contact@hdwlab.co.jp
    name: Human Dataware Lab. Co. Ltd.
    url: 'http://www.hdwlab.co.jp/'
  license:
    name: Apache-2.0
servers:
  - url: 'http://localhost:8080'
paths:
  /users:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  start:
                    type: number
                  limit:
                    type: number
                  length:
                    type: number
                  users:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        created_at:
                          type: string
                          minLength: 1
                        email:
                          type: string
                          minLength: 1
                        email_verified:
                          type: boolean
                        family_name:
                          type: string
                          minLength: 1
                        given_name:
                          type: string
                          minLength: 1
                        identities:
                          type: array
                          uniqueItems: true
                          minItems: 1
                          items:
                            type: object
                            properties:
                              provider:
                                type: string
                                minLength: 1
                              user_id:
                                type: string
                                minLength: 1
                              connection:
                                type: string
                                minLength: 1
                              isSocial:
                                type: boolean
                            required:
                              - provider
                              - user_id
                              - connection
                              - isSocial
                        locale:
                          type: string
                          minLength: 1
                        name:
                          type: string
                          minLength: 1
                        nickname:
                          type: string
                          minLength: 1
                        picture:
                          type: string
                          minLength: 1
                        updated_at:
                          type: string
                          minLength: 1
                        user_id:
                          type: string
                          minLength: 1
                        last_login:
                          type: string
                          minLength: 1
                        last_ip:
                          type: string
                          minLength: 1
                        logins_count:
                          type: number
                        app_metadata:
                          type: object
                          properties:
                            roles:
                              type: array
                              items:
                                type: object
                          required:
                            - roles
                        roles:
                          type: array
                          items:
                            type: string
                      required:
                        - created_at
                        - email
                        - email_verified
                        - family_name
                        - given_name
                        - locale
                        - name
                        - nickname
                        - picture
                        - updated_at
                        - user_id
                        - last_login
                        - last_ip
                        - logins_count
                  total:
                    type: number
                required:
                  - start
                  - limit
                  - length
                  - users
                  - total
              examples: {}
      operationId: getUsers
      description: Get user list
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Auth0 token
components:
  schemas: {}
tags:
  - name: record
