openapi: 3.0.2
info:
  title: permission store
  version: '1.0'
  description: Permision manage APIs
  contact:
    email: contact@hdwlab.co.jp
    name: Human Dataware Lab. Co. Ltd.
    url: 'http://www.hdwlab.co.jp/'
  license:
    name: Apache-2.0
servers:
  - url: 'http://localhost:8080'
paths:
  /users:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  properties:
                    user_id:
                      type: string
                      minLength: 1
                    email:
                      type: string
                      minLength: 1
                    email_verified:
                      type: boolean
                    username:
                      type: string
                      minLength: 1
                    phone_number:
                      type: string
                      minLength: 1
                    phone_verified:
                      type: boolean
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    identities:
                      type: array
                      uniqueItems: true
                      minItems: 1
                      items:
                        type: object
                        properties:
                          connection:
                            type: string
                            minLength: 1
                          user_id:
                            type: string
                            minLength: 1
                          provider:
                            type: string
                            minLength: 1
                          isSocial:
                            type: boolean
                        required:
                          - connection
                          - user_id
                          - provider
                          - isSocial
                    app_metadata:
                      type: object
                    user_metadata:
                      type: object
                    picture:
                      type: string
                    name:
                      type: string
                    nickname:
                      type: string
                    multifactor:
                      type: array
                      items:
                        type: object
                    last_ip:
                      type: string
                    last_login:
                      type: string
                    logins_count:
                      type: number
                    blocked:
                      type: boolean
                    given_name:
                      type: string
                    family_name:
                      type: string
                    roles:
                      type: array
                      items:
                        type: string
                  required:
                    - user_id
                    - email
                    - email_verified
                    - username
                    - phone_number
                    - phone_verified
                    - created_at
                    - updated_at
                    - identities
                    - app_metadata
                    - user_metadata
                    - picture
                    - name
                    - nickname
                    - multifactor
                    - last_ip
                    - last_login
                    - logins_count
                    - blocked
                    - given_name
                    - family_name
              examples:
                example-1:
                  value:
                    - created_at: '2020-12-14T02:23:54.752Z'
                      email: tarou.hdl@hdwlab.co.jp
                      email_verified: true
                      family_name: HDL
                      given_name: Tarou
                      identities:
                        - provider: google-oauth2
                          user_id: '1080259335512354542332'
                          connection: google-oauth2
                          isSocial: true
                      locale: ja
                      name: Tarou HDL
                      nickname: THDL
                      picture: 'https://lh5.googleusercontent.com/photo.jpg'
                      updated_at: '2021-03-08T07:51:52.456Z'
                      user_id: google-oauth2|1080259335512354542332
                      last_login: '2021-03-08T07:51:52.455Z'
                      last_ip: 133.6.156.91
                      logins_count: 5
                      roles:
                        - admin
                        - normal-user
      operationId: getUsers
      description: Get user list
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Auth0 token
components:
  schemas: {}
tags:
  - name: record
