name: Test for generating OpenAPI client

on: [push]

jobs:
  generate-openapi-client:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Iinstall openapi-typescript-codegen
        run: npm install -g openapi-typescript-codegen

      - name: Generate OpenAPI clients
        shell: bash
        run: |
          export PATH=${PATH}:$(npm config get prefix)/bin
          for schema in $(find ./schemas/apis -name *.yaml)
          do
            echo "Generating ${schema}..."
            openapi --input ${schema} --output /tmp/client || exit 1
          done
